[package]
name = "url"
version = "0.1.0"
edition = "2024"

[[bin]]
name = 'extract-url'
path = 'src/bin/extract-url.rs'

[[bin]]
name = 'has-url'
path = 'src/bin/has-url.rs'

[dependencies]
anyhow = "1.0.82"
shared = { path = "../shared" }
