[package]
name = "string"
version = "0.1.0"
edition = "2021"

[[bin]]
name = 'string-format'
path = 'src/bin/string-format.rs'

[[bin]]
name = 'extract-phone'
path = 'src/bin/extract-phone.rs'

[dependencies]
anyhow.workspace = true
regex.workspace = true
shared.workspace = true
